# Generated by Django 2.1.7 on 2019-03-31 06:14

import ModelsApp.Helpers.UploadsTo
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fuga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta')], verbose_name='Categoría')),
                ('recomendacion', models.CharField(choices=[('REP', 'Reparar'), ('REM', 'Remplazar'), ('OTR', 'Otra')], max_length=3, verbose_name='Recomendación')),
                ('refacciones_comentarios', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Refacciones y/o comentarios')),
                ('nadp', models.BooleanField(default=False, verbose_name='Not Available During Production (NADP)')),
                ('estatus', models.SmallIntegerField(choices=[(1, 'Registrado'), (2, 'Corregido')], default=1, verbose_name='Estatus')),
                ('punto_x', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Coordenada X')),
                ('punto_y', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Coordenada Y')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Area', verbose_name='Área')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenFuga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('imagen', models.ImageField(upload_to=ModelsApp.Helpers.UploadsTo.get_full_path_img_fuga, verbose_name='Imagen de la fuga')),
                ('fuga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Fuga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Area', verbose_name='Área')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Planta')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('plano', models.FileField(upload_to=ModelsApp.Helpers.UploadsTo.get_full_path, verbose_name='Plano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Empresa', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenecerá el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fuga',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Maquina', verbose_name='Máquina'),
        ),
        migrations.AddField(
            model_name='fuga',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Registró'),
        ),
        migrations.AddField(
            model_name='fuga',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='area',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Planta', verbose_name='Planta'),
        ),
    ]
