# Generated by Django 2.1.7 on 2019-03-08 22:40

import ModelsApp.Helpers.UploadsTo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Planta')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('plano', models.FileField(upload_to=ModelsApp.Helpers.UploadsTo.get_full_path, verbose_name='Plano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Empresa', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
