# Generated by Django 2.1.7 on 2019-03-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenecerá el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Empresa', verbose_name='Empresa'),
        ),
    ]
