# Generated by Django 2.1.7 on 2019-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_auto_20190331_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuga',
            name='categoria',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='fuga',
            name='punto_x',
            field=models.DecimalField(decimal_places=18, max_digits=26, verbose_name='Coordenada X'),
        ),
        migrations.AlterField(
            model_name='fuga',
            name='punto_y',
            field=models.DecimalField(decimal_places=18, max_digits=26, verbose_name='Coordenada Y'),
        ),
    ]
