# Generated by Django 2.1.7 on 2019-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0003_auto_20190331_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='flujo_total',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='Flujo Total'),
        ),
    ]
