# Generated by Django 2.1.7 on 2019-03-25 15:53

import ModelsApp.Helpers.UploadsTo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0005_auto_20190318_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFuga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('imagen', models.ImageField(upload_to=ModelsApp.Helpers.UploadsTo.get_full_path, verbose_name='Imagen de la fuga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fuga',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Registró'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuga',
            name='nadp',
            field=models.BooleanField(default=False, verbose_name='Not Available During Production (NADP)'),
        ),
        migrations.AddField(
            model_name='imagenfuga',
            name='fuga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelsApp.Fuga'),
        ),
    ]
